<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SystemSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('system_settings')->insert([

            [
                'key' => 'low_stock_count',
                'value' => '0',
                'value_options' => null,
                'type' => 'integer',
                'group' => 'inventory',
                'description' => 'When the available product quantity goes below this value, the product will be marked as low stock.',
                'is_autogenerated' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'auto_sku_generation',
                'value' => true,
                'value_options' => null,
                'type' => 'boolean',
                'group' => 'product',
                'description' => 'Select if the product SKU should be auto-generated by the system or entered manually.',
                'is_autogenerated' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ], [
                'key' => 'test-key',
                'value' => 'test1',
                'value_options' => 'test1,test2,test3',
                'type' => 'enum',
                'group' => 'product',
                'description' => 'Select if the product SKU should be auto-generated by the system or entered manually.',
                'is_autogenerated' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
