<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('system_settings', function (Blueprint $table) {
            $table->id();

            // Identification
            $table->string('key')->unique();   // e.g. inventory.low_stock_count
            $table->text('value')->nullable(); // stored as string / json
            $table->string('value_options')->nullable(); // small note that will be helpful to insert/calculate value for user

            // Type handling (important)
            $table->enum('type', ['string', 'integer', 'boolean', 'enum', 'json'])->default('string');

            // Description & control
            $table->string('group')->nullable(); // inventory, order, ui, system
            $table->text('description')->nullable();

            // System control
            $table->boolean('is_autogenerated')->default(false); // value generated by system vs manual

            $table->timestamps();

            $table->index(['group', 'key']);
        });

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
};
